
services:
  api-gateway:
    build:
      context: . # ← Sets root as build context
      dockerfile: apiGateway/Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=4000
      - USER_SERVICE=http://user-service:3001
      - SERVICES_SERVICE=http://services-service:3002
      - EVENT_SERVICE=http://event-service:3003
      - BOOKING_SERVICE=http://booking-service:3004
      - CHAT_SERVICE=http://chat-service:3005
      - WALLET_SERVICE=http://wallet-service:3006
      - FRONTEND=http://nginx
      - JWT_ACCESS_SECRET=sreedeviEventPlannerApplicationAccessToken
      - JWT_REFRESH_SECRET=sreedeviEventPlannerApplicationRefreshToken
      - GRPC_USER_SERVER=user-service:50051
      - REDIS_CONNECTION_STRING=redis://redis:6379
    ports:
      - "4000:4000"
    networks:
      - event_planner_network
    depends_on:
      - user-service
      - redis

  user-service:
    build:
      context: .
      dockerfile: backend/user/Dockerfile
    ports:
      - "50051:50051"
    environment:
      - PORT=3001
      - NODE_ENV=production
      - JWT_ACCESS_SECRET=sreedeviEventPlannerApplicationAccessToken
      - JWT_REFRESH_SECRET=sreedeviEventPlannerApplicationRefreshToken
      - GOOGLE_ID=464375724320-2aug4rpcgj3qv8rnjraa0uu3ikjjbuqt.apps.googleusercontent.com
      - GOOGLE_SECRET=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
      # - SES_ACCESSKEY=AKIAW3MED76JNLSSHXVB
      # - SES_SECRETACCESSKEY=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
      - EMAIL_APP_PASSWORD=gdcy mpbc hgvy nhbq
      - EMAIL_USER=sreedevisooraj15@gmail.com
      # - EMAIL_URL=http://localhost/api/
      # - GOOGLE_CALLBACK_URL=http://localhost/api/user/auth/google/callback
      - EMAIL_URL=https://dreamevents.shop/api/
      - GOOGLE_CALLBACK_URL=https://dreamevents.shop/api/user/auth/google/callback
      - SESSION_SECRET_KEY=eventplannerapplication
      - GRPC_USER_SERVER=user-service:50051
      - MONGO_URL=mongodb://mongodb:27017/userService
      - REDIS_CONNECTION_STRING=redis://redis:6379
      - RESEND_APIKEY=re_ZxZz33z5_G8MRFepj3EoBhYnXhCBx6C3D
      - RESEND_EMAIL=noreply@dreamevents.shop
    networks:
      - event_planner_network
    depends_on:
      - mongodb
      - redis

  services-service:
    build:
      context: .
      dockerfile: backend/eventServices/Dockerfile
    ports:
      - "50052:50052"
    environment:
      - PORT=3002
      # - SERVICE_IMG_URL=http://nginx/api/service/uploads/ # Add nginx prefix
      - EMAIL_APP_PASSWORD=gdcy mpbc hgvy nhbq
      - EMAIL_USER=sreedevisooraj15@gmail.com
      - CLOUDINARY_CLOUD_NAME=dqsfjbusg
      - CLOUDINARY_API_KEY=854145994395918
      - CLOUDINARY_API_SECRET=qyxATSp5Lb2CEZ-DhYaII2YVpKk
      - MONGO_URL=mongodb://mongodb:27017/serviceService
      - GRPC_SERVICE_SERVER=services-service:50052
      - GRPC_USER_SERVER=user-service:50051
      - GRPC_EVENT_SERVER=event-service:50053
      - GRPC_WALLET_SERVER=wallet-service:50054
      - RESEND_APIKEY=re_ZxZz33z5_G8MRFepj3EoBhYnXhCBx6C3D
      - RESEND_EMAIL=noreply@dreamevents.shop
    networks:
      - event_planner_network
    depends_on:
      - mongodb

  event-service:
    build:
      context: .
      dockerfile: backend/events/Dockerfile
    ports:
      - "50053:50053"
    environment:
      - PORT=3003
      # - EVENT_IMG_URL=http://nginx/api/event/uploads/ # Add nginx prefix
      - EMAIL_APP_PASSWORD=gdcy mpbc hgvy nhbq
      - EMAIL_USER=sreedevisooraj15@gmail.com
      - CLOUDINARY_CLOUD_NAME=dqsfjbusg
      - CLOUDINARY_API_KEY=854145994395918
      - CLOUDINARY_API_SECRET=qyxATSp5Lb2CEZ-DhYaII2YVpKk
      - MONGO_URL=mongodb://mongodb:27017/eventService
      - GRPC_EVENT_SERVER=event-service:50053
      - GRPC_USER_SERVER=user-service:50051
      - GRPC_SERVICE_SERVER=services-service:50052
      - GRPC_WALLET_SERVER=wallet-service:50054
      - RESEND_APIKEY=re_ZxZz33z5_G8MRFepj3EoBhYnXhCBx6C3D
      - RESEND_EMAIL=noreply@dreamevents.shop
    networks:
      - event_planner_network
    depends_on:
      - mongodb

  booking-service:
    build:
      context: .
      dockerfile: backend/booking/Dockerfile
    environment:
      - PORT=3004
      - EMAIL_APP_PASSWORD=gdcy mpbc hgvy nhbq
      - EMAIL_USER=sreedevisooraj15@gmail.com
      - RAZORPAY_KEY_ID=rzp_test_85xo26IPuPICSY
      - RAZORPAY_SECRET=7r0r5ty9wj15t69rxcbQtzkL
      - MONGO_URL=mongodb://mongodb:27017/bookingService
      - GRPC_USER_SERVER=user-service:50051
      - GRPC_SERVICE_SERVER=services-service:50052
      - GRPC_EVENT_SERVER=event-service:50053
      - GRPC_WALLET_SERVER=wallet-service:50054
      - RESEND_APIKEY=re_ZxZz33z5_G8MRFepj3EoBhYnXhCBx6C3D
      - RESEND_EMAIL=noreply@dreamevents.shop
    networks:
      - event_planner_network
    depends_on:
      - mongodb

  chat-service:
    build:
      context: .
      dockerfile: backend/chat/Dockerfile
    environment:
      - PORT=3005
      - CLOUDINARY_CLOUD_NAME=dqsfjbusg
      - CLOUDINARY_API_KEY=854145994395918
      - CLOUDINARY_API_SECRET=qyxATSp5Lb2CEZ-DhYaII2YVpKk
      - MONGO_URL=mongodb://mongodb:27017/chatService
      - GRPC_USER_SERVER=user-service:50051
      - GRPC_SERVICE_SERVER=services-service:50052
      - GRPC_EVENT_SERVER=event-service:50053
      - GRPC_WALLET_SERVER=wallet-service:50054
    networks:
      - event_planner_network
    depends_on:
      - mongodb

  wallet-service:
    build:
      context: .
      dockerfile: backend/wallet/Dockerfile
    ports:
      - "50054:50054"
    environment:
      - PORT=3006
      - MONGO_URL=mongodb://mongodb:27017/walletService
      - GRPC_USER_SERVER=user-service:50051
      - GRPC_SERVICE_SERVER=services-service:50052
      - GRPC_EVENT_SERVER=event-service:50053
      - GRPC_WALLET_SERVER=wallet-service:50054
      - RESEND_APIKEY=re_ZxZz33z5_G8MRFepj3EoBhYnXhCBx6C3D
      - RESEND_EMAIL=noreply@dreamevents.shop
    networks:
      - event_planner_network
    depends_on:
      - mongodb

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - ./frontend/dist/browser:/app/frontend/dist/browser
    networks:
      - event_planner_network
    
  nginx:
    # image: nginx:latest
    build:
      context: .
      dockerfile: frontend/Dockerfile  # Build Nginx with Angular output
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ./frontend/dist/browser:/usr/share/nginx/html
      - /etc/letsencrypt:/etc/letsencrypt:ro
    entrypoint: [ "nginx", "-g", "daemon off;" ] # Skip entrypoint scripts
    depends_on:
      - frontend
      - api-gateway
    networks:
      - event_planner_network

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command:
      - --bind 0.0.0.0 # ← Critical for Docker networking.By default, Redis binds to 127.0.0.1, making it unreachable from other containers unless explicitly set to 0.0.0.0.
    networks:
      - event_planner_network

  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db 
    networks:
      - event_planner_network

volumes:
  mongodb_data: # Persist MongoDB
  redis_data:
    # Persist Redis (optional)

networks:
  event_planner_network:
    name: event_planner_network
    driver: bridge
