export const Menus=[
    {
        path:'dashboard',
        text:'Home',
        roles:['user','admin','provider']
    },
    {
        path:'services',
        text:'Services',
        roles:['user','admin','provider']
    },
    {
        path:'favorites',
        text:'Favorites',
        roles:['user']
    },
    {
        path:'sales',
        text:'Sales',
        roles:['admin']
    },
    {
        path:'booking',
        text:'Booking',
        roles:['user']
    },
]